spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=fb49f322f2b75b
spring.mail.password=600b627f136f7f
mail.from=climalert@service.com

weatherapi.base-url=http://api.weatherapi.com/v1
weatherapi.key=ad6e6426ed8940ac80e134930260307